// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0w-pjM7tCDHaXmVgBOhjqneHuZnGPn20',
    appId: '1:178803796211:web:15c239ee2cff83e76bef86',
    messagingSenderId: '178803796211',
    projectId: 'assignment-manager-1246f',
    authDomain: 'assignment-manager-1246f.firebaseapp.com',
    storageBucket: 'assignment-manager-1246f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBg7ZVY1R6Nap8NQ0FkmxJpe4r9z3BZSs',
    appId: '1:178803796211:android:f31858f0b5425da36bef86',
    messagingSenderId: '178803796211',
    projectId: 'assignment-manager-1246f',
    storageBucket: 'assignment-manager-1246f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPZ5gcxV1caO-XjMAwm6p3JLNTqka53M',
    appId: '1:178803796211:ios:f5bb833ee6c026216bef86',
    messagingSenderId: '178803796211',
    projectId: 'assignment-manager-1246f',
    storageBucket: 'assignment-manager-1246f.firebasestorage.app',
    iosBundleId: 'com.example.assignmentManager',
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPZ5gcxV1caO-XjMAwm6p3JLNTqka53M',
    appId: '1:178803796211:ios:f5bb833ee6c026216bef86',
    messagingSenderId: '178803796211',
    projectId: 'assignment-manager-1246f',
    storageBucket: 'assignment-manager-1246f.firebasestorage.app',
    iosBundleId: 'com.example.assignmentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0w-pjM7tCDHaXmVgBOhjqneHuZnGPn20',
    appId: '1:178803796211:web:cc69bd0b9e898c336bef86',
    messagingSenderId: '178803796211',
    projectId: 'assignment-manager-1246f',
    authDomain: 'assignment-manager-1246f.firebaseapp.com',
    storageBucket: 'assignment-manager-1246f.firebasestorage.app',
  );
}
